config/routes.rb
Primero::Application.routes.draw do
  resources :eventos

  resources :eventos2s

  get "home/index"

   root :to => 'home#index'

end

app/models/evento.rb
class Evento < ActiveRecord::Base
end

app/models/eventos2.rb
class Eventos2 < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/eventos2s_controller.rb
class Eventos2sController < ApplicationController
  # GET /eventos2s
  # GET /eventos2s.json
  def index
    @eventos2s = Eventos2.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @eventos2s }
    end
  end

  # GET /eventos2s/1
  # GET /eventos2s/1.json
  def show
    @eventos2 = Eventos2.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @eventos2 }
    end
  end

  # GET /eventos2s/new
  # GET /eventos2s/new.json
  def new
    @eventos2 = Eventos2.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @eventos2 }
    end
  end

  # GET /eventos2s/1/edit
  def edit
    @eventos2 = Eventos2.find(params[:id])
  end

  # POST /eventos2s
  # POST /eventos2s.json
  def create
    @eventos2 = Eventos2.new(params[:eventos2])

    respond_to do |format|
      if @eventos2.save
        format.html { redirect_to @eventos2, notice: 'Eventos2 was successfully created.' }
        format.json { render json: @eventos2, status: :created, location: @eventos2 }
      else
        format.html { render action: "new" }
        format.json { render json: @eventos2.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /eventos2s/1
  # PUT /eventos2s/1.json
  def update
    @eventos2 = Eventos2.find(params[:id])

    respond_to do |format|
      if @eventos2.update_attributes(params[:eventos2])
        format.html { redirect_to @eventos2, notice: 'Eventos2 was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @eventos2.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /eventos2s/1
  # DELETE /eventos2s/1.json
  def destroy
    @eventos2 = Eventos2.find(params[:id])
    @eventos2.destroy

    respond_to do |format|
      format.html { redirect_to eventos2s_url }
      format.json { head :ok }
    end
  end
end

app/controllers/eventos_controller.rb
class EventosController < ApplicationController
  # GET /eventos
  # GET /eventos.json
  def index
    @eventos = Evento.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @eventos }
    end
  end

  # GET /eventos/1
  # GET /eventos/1.json
  def show
    @evento = Evento.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @evento }
    end
  end

  # GET /eventos/new
  # GET /eventos/new.json
  def new
    @evento = Evento.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @evento }
    end
  end

  # GET /eventos/1/edit
  def edit
    @evento = Evento.find(params[:id])
  end

  # POST /eventos
  # POST /eventos.json
  def create
    @evento = Evento.new(params[:evento])

    respond_to do |format|
      if @evento.save
        format.html { redirect_to @evento, notice: 'Evento was successfully created.' }
        format.json { render json: @evento, status: :created, location: @evento }
      else
        format.html { render action: "new" }
        format.json { render json: @evento.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /eventos/1
  # PUT /eventos/1.json
  def update
    @evento = Evento.find(params[:id])

    respond_to do |format|
      if @evento.update_attributes(params[:evento])
        format.html { redirect_to @evento, notice: 'Evento was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @evento.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /eventos/1
  # DELETE /eventos/1.json
  def destroy
    @evento = Evento.find(params[:id])
    @evento.destroy

    respond_to do |format|
      format.html { redirect_to eventos_url }
      format.json { head :ok }
    end
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/eventos2s_helper.rb
module Eventos2sHelper
end

app/helpers/eventos_helper.rb
module EventosHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/Eventos2/_form.html.erb
<%= form_for(@eventos2) do |f| %>
  <% if @eventos2.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@eventos2.errors.count, "error") %> prohibited this eventos2 from being saved:</h2>

      <ul>
      <% @eventos2.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :nombre %><br />
    <%= f.text_field :nombre %>
  </div>
  <div class="field">
    <%= f.label :titulo %><br />
    <%= f.text_field :titulo %>
  </div>
  <div class="field">
    <%= f.label :fecha %><br />
    <%= f.datetime_select :fecha %>
  </div>
  <div class="field">
    <%= f.label :contenido %><br />
    <%= f.text_field :contenido %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/Eventos2/edit.html.erb
<h1>Editing eventos2</h1>

<%= render 'form' %>

<%= link_to 'Show', @eventos2 %> |
<%= link_to 'Back', eventos2s_path %>

app/views/Eventos2/index.html.erb
<h1>Listing eventos2s</h1>

<table>
  <tr>
    <th>Nombre</th>
    <th>Titulo</th>
    <th>Fecha</th>
    <th>Contenido</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @eventos2s.each do |eventos2| %>
  <tr>
    <td><%= eventos2.nombre %></td>
    <td><%= eventos2.titulo %></td>
    <td><%= eventos2.fecha %></td>
    <td><%= eventos2.contenido %></td>
    <td><%= link_to 'Show', eventos2 %></td>
    <td><%= link_to 'Edit', edit_eventos2_path(eventos2) %></td>
    <td><%= link_to 'Destroy', eventos2, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Eventos2', new_eventos2_path %>

app/views/Eventos2/new.html.erb
<h1>New eventos2</h1>

<%= render 'form' %>

<%= link_to 'Back', eventos2s_path %>

app/views/Eventos2/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Nombre:</b>
  <%= @eventos2.nombre %>
</p>

<p>
  <b>Titulo:</b>
  <%= @eventos2.titulo %>
</p>

<p>
  <b>Fecha:</b>
  <%= @eventos2.fecha %>
</p>

<p>
  <b>Contenido:</b>
  <%= @eventos2.contenido %>
</p>


<%= link_to 'Edit', edit_eventos2_path(@eventos2) %> |
<%= link_to 'Back', eventos2s_path %>

app/views/eventos/_form.html.erb
<%= form_for(@evento) do |f| %>
  <% if @evento.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@evento.errors.count, "error") %> prohibited this evento from being saved:</h2>

      <ul>
      <% @evento.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :nombre %><br />
    <%= f.text_field :nombre %>
  </div>
  <div class="field">
    <%= f.label :titulo %><br />
    <%= f.text_field :titulo %>
  </div>
  <div class="field">
    <%= f.label :fecha %><br />
    <%= f.datetime_select :fecha %>
  </div>
  <div class="field">
    <%= f.label :contenido %><br />
    <%= f.text_field :contenido %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/eventos/edit.html.erb
<h1>Editing evento</h1>

<%= render 'form' %>

<%= link_to 'Show', @evento %> |
<%= link_to 'Back', eventos_path %>

app/views/eventos/index.html.erb
<h1>Listing eventos</h1>

<table>
  <tr>
    <th>Nombre</th>
    <th>Titulo</th>
    <th>Fecha</th>
    <th>Contenido</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @eventos.each do |evento| %>
  <tr>
    <td><%= evento.nombre %></td>
    <td><%= evento.titulo %></td>
    <td><%= evento.fecha %></td>
    <td><%= evento.contenido %></td>
    <td><%= link_to 'Show', evento %></td>
    <td><%= link_to 'Edit', edit_evento_path(evento) %></td>
    <td><%= link_to 'Destroy', evento, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Evento', new_evento_path %>

app/views/eventos/new.html.erb
<h1>New evento</h1>

<%= render 'form' %>

<%= link_to 'Back', eventos_path %>

app/views/eventos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Nombre:</b>
  <%= @evento.nombre %>
</p>

<p>
  <b>Titulo:</b>
  <%= @evento.titulo %>
</p>

<p>
  <b>Fecha:</b>
  <%= @evento.fecha %>
</p>

<p>
  <b>Contenido:</b>
  <%= @evento.contenido %>
</p>


<%= link_to 'Edit', edit_evento_path(@evento) %> |
<%= link_to 'Back', eventos_path %>

app/views/home/index.html.erb
<h1>Hello, Rails!</h1>
<%= link_to "Eventos", eventos_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Primero</title>
  <%= stylesheet_link_tag    "application" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>